### ISSUE TITLE
Remove technical debt

### ISSUE THREAD

**Issue by michaeldev5** [paraspell/xcm-tools#291]
This includes refactoring of code by following subtasks:

- [x] Remove unused createTextLabel function - Fixed in #294 
- [x] Make sure WalletProvider has only one export to remove eslint warning #307 
- [x] Use Apollo Graphql instead of Graphql request #307 
- [x] In Parachain.tsx extract lightenColor function to utils #307 
- [x] Remove unused libraries from frontend #307 
- [x] Remove unused commented out code #307 
- [x] Remove unused queries on backend #307 
- [x] Add all strings in UI to localization file #307 
- [x] Add proper type to updateMessageDto instead of any #307 
- [x] Add auto deploy to XCM Visualizator - #308 
- [x] Add unit tests for service methods on backend - #309
- [x] Fix disabled eslint rule in AccountsAmountPlot - #310
- [x] Update apps-config in visualizator-fe. This requires adding new logos for new parachains - #311
- [x] Add e2e tests #313

**Comment by dudo50** [comment]
Closing the issue as all tasks were now resolved and technical debt is no more ✨
